<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- net6.0 required - cTrader.Automate and cTrader CLI only support .NET 6 algos -->
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.0.17" />
  </ItemGroup>

</Project>